# Generated by Django 3.0.5 on 2020-05-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeedupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedUpdate',
            new_name='ProfileFeedItem',
        ),
    ]
